services:
  backend:
    build: .
    container_name: resplanet-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery:
    build: .
    container_name: resplanet-celery
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: celery -A app.tasks.celery_app worker --loglevel=info

  db:
    image: pgvector/pgvector:pg16
    container_name: resplanet-db
    environment:
      POSTGRES_USER: resplanet
      POSTGRES_PASSWORD: resplanet123
      POSTGRES_DB: resplanet_db
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: resplanet-redis
    ports:
      - "6379:6379"
